[workspace]
resolver = "2"
members = [
  "crates/temp-rs-dylib-loader",
  "crates/temp-rs-compiler",
  "crates/temp-rs-core",
  "crates/temp-rs-cli",
]

[workspace.dependencies]
anyhow = "1.0.104"
libc = "1.0.0-alpha.4"
tempfile = "3.27.0"
rustyline = "18.0.1"
syn = { version = "3.0.6", features = ["full"] }

temp-rs-dylib-loader = { path = "crates/temp-rs-dylib-loader" }
temp-rs-compiler = { path = "crates/temp-rs-compiler" }
temp-rs-core = { path = "crates/temp-rs-core" }
